### ISSUE TITLE
Introduce render passes

### ISSUE THREAD

**Issue by Kangz** [google/nxt-standalone#7]
NXT uses a default framebuffer style of rendering as a placeholder for render passes. For automated testing we need to read-back what was rendered so we need to add render passes.

TODO (@kainino0x):
- [x] First design #14 
- [x] First implementation (Metal backend) #14 
- [x] Render-to-texture demo #14 
- [x] Update other demos #14 
- [x] Update glTFViewer #39 
- [ ] Check fragment shader output types matches render pass metadata
- [ ] Testing?
- [x] OpenGL backend #73 
- [ ] Any TODOs I added in #14 - especially the backbuffer hack (blocked on WSI)
- [ ] load/store operations

**Comment by kainino0x** [comment]
First implementation is done in #14.

In particular:
* First API design (many features missing, including input attachments)
* Metal implementation (no OpenGL yet)
* Render-to-texture demo (a little broken until we have depth buffers)
* Update examples to use render passes

TODO:
- [ ] Check fragment output matches render pass
- [ ] Testing?
- [ ] OpenGL backend
- [ ] Any TODOs I added in #14 - especially the backbuffer hack (blocked on WSI)
